### PR TITLE
Add support for the DS record

### PR DESCRIPTION
**Pull request by baest**
Also updated tests to add a new DS record for a sub zone along with updates since an existing DS records is now handled

### CODE REVIEW

**Comment by baest** [comment]
Is superseded by https://github.com/octodns/octodns-powerdns/pull/50 if https://github.com/octodns/octodns/pull/1065 is merged

**Comment by ross** [comment]
> Is superseded by #50 if [octodns/octodns#1065](https://github.com/octodns/octodns/pull/1065) is merged

We'll need to stick with this one for now since it will work with older versions of octoDNS. 

Once https://github.com/octodns/octodns/pull/1065#pullrequestreview-1634283518 is merged and released we can merge https://github.com/octodns/octodns-powerdns/pull/50 if/when we're OK with putting a hard requirement on the (new) version of octoDNS.

**Review by ross — APPROVED** [review]

**Comment by ross** [comment]
Thanks

**Comment by baest** [comment]
Thank you for merging it (and doing so so quickly)!

**Pull request merged**
